service: uuid

frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    reloadHandler: true

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    NODE_OPTIONS: "--enable-source-maps"

functions:
  uuid:
    handler: handler.uuid
    events:
      - http:
          path: uuid
          method: get
    layers:
      - { Ref: UuidLambdaLayer }

layers:
  uuid:
    path: ./
    description: "UUID Dependencies"
