service: uuid

frameworkVersion: '3'

plugins:
  - serverless-layers
  - serverless-deployment-bucket


custom:
  serverless-layers:
    layersDeploymentBucket: uuid-bucket
    dependenciesPath: ./package.json

provider:
  name: aws
  runtime: nodejs16.x

functions:
  uuid:
    handler: handler.uuid
