service: uuid

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  uuid:
    handler: handler.uuid
    layers:
      - { Ref: UuidLambdaLayer }

layers:
  uuid:
    path: ./
    description: "UUID Dependencies"
